# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/camera/Q/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal7870-common/camera/Q


PRODUCT_PACKAGES += \
    libstainkiller \
    libuniplugin
