# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/samsung_slsi_q/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal7870-common/samsung_slsi_q

PRODUCT_COPY_FILES += \
    vendor/samsung/universal7870-common/samsung_slsi_q/proprietary/vendor/lib/libhwc2on1adapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwc2on1adapter.so \
    vendor/samsung/universal7870-common/samsung_slsi_q/proprietary/vendor/lib/libhwc2onfbadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwc2onfbadapter.so
