# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/gatekeeper/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal7870-common/gatekeeper


PRODUCT_PACKAGES += \
    gatekeeper.exynos7870
