# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/tee/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal7870-common/tee

PRODUCT_COPY_FILES += \
    vendor/samsung/universal7870-common/tee/proprietary/vendor/bin/mcDriverDaemon:$(TARGET_COPY_OUT_VENDOR)/bin/mcDriverDaemon