# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/media/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal7870-common/media

PRODUCT_COPY_FILES += \
    vendor/samsung/universal7870-common/media/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin
