# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/keymaster/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal7870-common/keymaster

PRODUCT_COPY_FILES += \
    vendor/samsung/universal7870-common/keymaster/proprietary/vendor/lib/hw/keystore.mdfpp.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.mdfpp.so \
    vendor/samsung/universal7870-common/keymaster/proprietary/vendor/lib/libkeymaster_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeymaster_helper.so \
    vendor/samsung/universal7870-common/keymaster/proprietary/vendor/lib/libkeymaster_mdfpp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeymaster_mdfpp.so
