# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/a6lte_audio/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a6lte j7velte j7xelte on7xelte j7popelteskt,$(TARGET_DEVICE)),)

endif
