# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/m10lte_audio/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a3y17lte j5y17lte j6lte j7y17lte m10lte gtaxlwifi gtaxllte,$(TARGET_DEVICE)),)

endif
