# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/a6lte_gnss/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a3y17lte j5y17lte a6lte j6lte j7velte j7xelte j7y17lte on7xelte m10lte j7popelteskt,$(TARGET_DEVICE)),)

endif
