# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/radio/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal7870-common/radio

PRODUCT_COPY_FILES += \
    vendor/samsung/universal7870-common/radio/proprietary/vendor/bin/secril_config_svc:$(TARGET_COPY_OUT_VENDOR)/bin/secril_config_svc \
    vendor/samsung/universal7870-common/radio/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/universal7870-common/radio/proprietary/vendor/etc/mtu-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtu-conf.xml \
    vendor/samsung/universal7870-common/radio/proprietary/vendor/etc/pdpcnt-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pdpcnt-conf.xml \

PRODUCT_PACKAGES += \
    libfloatingfeature \
    libril-samsung \
    libsec-ril-dsds \
    libsec-ril \
    libsecnativefeature \
    vendor.samsung.hardware.radio.bridge@2.0 \
    vendor.samsung.hardware.radio.bridge@2.0_vendor \
    vendor.samsung.hardware.radio.channel@2.0_vendor \
    vendor.samsung.hardware.radio@2.0_vendor \
    libaptX_encoder
