# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/samsung_slsi/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal7870-common/samsung_slsi

PRODUCT_COPY_FILES += \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib/hw/gralloc.exynos7870.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.exynos7870.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib/hw/hwcomposer.exynos7870.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.exynos7870.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib/libexynosgscaler.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynosgscaler.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib/libexynosscaler.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynosscaler.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib64/hw/gralloc.exynos7870.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.exynos7870.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib64/libexynosgscaler.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libexynosgscaler.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib64/libexynosscaler.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libexynosscaler.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib/hw/memtrack.exynos7870.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.exynos7870.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib/libcsc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcsc.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib/libexynosutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynosutils.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib/libexynosv4l2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynosv4l2.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib/libion_exynos.so:$(TARGET_COPY_OUT_VENDOR)/lib/libion_exynos.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib/libmpp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmpp.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib64/hw/memtrack.exynos7870.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/memtrack.exynos7870.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib64/libcsc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcsc.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib64/libexynosutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libexynosutils.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib64/libexynosv4l2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libexynosv4l2.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib64/libion_exynos.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libion_exynos.so \
    vendor/samsung/universal7870-common/samsung_slsi/proprietary/vendor/lib64/libmpp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmpp.so
