# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7870-common/sec_keymaster/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal7870-common/sec_keymaster


PRODUCT_PACKAGES += \
    keystore.mdfpp \
    libkeymaster_mdfpp \
    libkeymaster_helper
